# SPDX-License-Identifier: Apache-2.0
[package]
name = "cog-backend-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cog-core.workspace = true
cog-backend-api.workspace = true
cog-shm.workspace = true
